# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install -e .
  - pip install coveralls

script:
  - coverage run setup.py test
  - coverage report -m

after_script:
  coveralls --verbose
