# This is a conda environment.yml config file.
# See: https://github.com/conda/conda-env#environmentyml
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    # XXX Might not be necessary once
    # https://github.com/rtfd/readthedocs.org/pull/2368 is fixed.
    - pip:
        - sphinx >= 1.4
