# This is a conda environment.yml config file.
# See: https://github.com/conda/conda-env#environmentyml
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pip:
        - sphinx >= 1.4
